# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" # Options: "default", "air"
title                    : "Zexu Li"
title_separator          : "-"
name                     : &name "Zexu Li"
description              : &description "Zexu Li - PhD Candidate in Civil & Environmental Engineering"
url                      : "https://LoneStar97.github.io/Zexu_Li.github.io/" # The base hostname
baseurl                  : "/Zexu_Li.github.io" # IMPORTANT: Matches your repository name. If you rename your repo to 'LoneStar97.github.io', change this to "" (empty quotes).
repository               : "LoneStar97/Zexu_Li.github.io"
teaser                   : # filename of teaser image for social media

# Site Author - Sidebar Data
author:
  avatar           : "profile.png" # You MUST upload a photo named 'profile.png' to your repository's main folder
  name             : "Zexu Li"
  pronouns         : "he/him" 
  bio              : "PhD Candidate<br>University of Pittsburgh"
  location         : "Pittsburgh, PA"
  employer         : "University of Pittsburgh"
  email            : "zel45@pitt.edu"
  
  # Academic websites 
  googlescholar    : "https://scholar.google.com/citations?user=od3WvyAAAAAJ&hl=en"
  researchgate     : "https://www.researchgate.net/profile/Zexu-Li-5"
  orcid            : # Add URL if you have one
  github           : "LoneStar97"
  linkedin         : # Add URL if you have one
  twitter          : # Add URL if you have one

# Footer Links
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:zel45@pitt.edu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/LoneStar97"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=od3WvyAAAAAJ&hl=en"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Zexu-Li-5"

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-redirect-from
  - jemoji

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Publication Categories
publication_category:
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'
  preprints:
    title: 'Preprints'

# Analytics
analytics:
  provider         : false 
  google:
    tracking_id    :
